### ISSUE TITLE
@vx/grid: Is it possible to style nth element with columnLineStyle

### ISSUE THREAD

**Issue by Kiennyo** [hshoff/vx#657]
Hi there :)

Newbie question: is it possible to add nth child styling ? 
```
<Grid
    // vx-columns:nth-child(3) {stroke: red}
    columnLineStyle={{stroke: 'blue'}}
    ...
/>
```

Thank you for your time

**Comment by hshoff** [comment]
Hi @Kiennyo, this is possible with css:

```jsx
<Grid
  className="my-custom-grid"
  ...
/>
```
```css
.my-custom-grid.vx-columns > .vx-line:nth-child(3) {
    stroke: red;
}
```
